import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';
const scene = new THREE.Scene()
const axes = new THREE.AxesHelper(8)
scene.add(axes)
const width = window.innerWidth;
const height = window.innerHeight;
 const camera = new THREE.PerspectiveCamera(
    50,
    width / innerHeight,
    0.1,
    2000
 )
 camera.position.set(12,6,0)
//table
 const geometry = new THREE.BoxGeometry(8, 0.5, 6)
 const material = new THREE.MeshBasicMaterial({color : 0x3D0C02})
 const cube =  new THREE.Mesh(geometry,material)
 cube.position.set(0,4.5,0)
 const geometry1 = new THREE.BoxGeometry(0.5, 5, 0.5)
 const material1 = new THREE.MeshBasicMaterial({color : 0x704214})
 const regtangle =  new THREE.Mesh(geometry1,material1)
 regtangle.position.set(3.3,2,2.5)
 const geometry2 = new THREE.BoxGeometry(0.5, 5, 0.5)
 const material2 = new THREE.MeshBasicMaterial({color : 0x704214})
 const regtangle2 =  new THREE.Mesh(geometry2,material2)
 regtangle2.position.set(-3.3,2,2.5)
 const geometry3 = new THREE.BoxGeometry(0.5, 5, 0.5)
 const material3 = new THREE.MeshBasicMaterial({color : 0x704214})
 const regtangle3 =  new THREE.Mesh(geometry3,material3)
 regtangle3.position.set(3.3,2,-2.5)
 const geometry4 = new THREE.BoxGeometry(0.5, 5, 0.5)
 const material4 = new THREE.MeshBasicMaterial({color : 0x704214})
 const regtangle4 =  new THREE.Mesh(geometry4,material4)
 regtangle4.position.set(-3.3,2,-2.5)
 const geo = new THREE.BoxGeometry(0.5, 0.5, 4.5)
 const mat = new THREE.MeshBasicMaterial({color : 0x704214})
 const under =  new THREE.Mesh(geo,mat)
 under.position.set(3.3,4,0)
 const geoo = new THREE.BoxGeometry(0.5, 0.5, 4.5)
 const matt = new THREE.MeshBasicMaterial({color : 0x704214})
 const underr =  new THREE.Mesh(geoo,matt)
 underr.position.set(3.3,1,0)
 const geo1 = new THREE.BoxGeometry(0.5, 0.5, 4.5)
 const mat1= new THREE.MeshBasicMaterial({color : 0x704214})
 const under1 =  new THREE.Mesh(geo1,mat1)
 under1.position.set(-3.3,4,0)
 const geo11 = new THREE.BoxGeometry(0.5, 0.5, 4.5)
 const mat11= new THREE.MeshBasicMaterial({color : 0x704214})
 const under11 =  new THREE.Mesh(geo11,mat11)
 under11.position.set(-3.3,1,0)
 const geo2 = new THREE.BoxGeometry(6.1, 0.5, 0.5)
 const mat2= new THREE.MeshBasicMaterial({color : 0x704214})
 const under2 =  new THREE.Mesh(geo2,mat2)
 under2.position.set(0,4,2.5)
 const geo3 = new THREE.BoxGeometry(6.1, 0.5, 0.5)
 const mat3= new THREE.MeshBasicMaterial({color : 0x704214})
 const under3 =  new THREE.Mesh(geo3,mat3)
 under3.position.set(0,4,-2.5)
//chair 1
 const geometryc1 = new THREE.BoxGeometry(3, 0.2, 2)
 const materialc1 = new THREE.MeshBasicMaterial({color : 0x5C3317})
 const cube1 =  new THREE.Mesh(geometryc1,materialc1)
 cube1.position.set(0,2.5,5)
 const geometryb = new THREE.BoxGeometry(2.8, 2.2, 0.2)
 const materialb = new THREE.MeshBasicMaterial({color : 0x7E3817})
 const cubeb =  new THREE.Mesh(geometryb,materialb)
 cubeb.position.set(0,3.5,6)
 const geometryl = new THREE.BoxGeometry(0.3, 3, 0.3)
 const materialL = new THREE.MeshBasicMaterial({color : 0x8A4117})
 const leg=  new THREE.Mesh(geometryl,materialL)
 leg.position.set(1.2,1,5.8)
 const geometryl2 = new THREE.BoxGeometry(0.3, 3, 0.3)
 const materialL2 = new THREE.MeshBasicMaterial({color : 0x8A4117})
 const leg2=  new THREE.Mesh(geometryl2,materialL2)
 leg2.position.set(1.2,1,4.2)
 const geometryl3 = new THREE.BoxGeometry(0.3, 3, 0.3)
 const materialL3 = new THREE.MeshBasicMaterial({color : 0x8A4117})
 const leg3=  new THREE.Mesh(geometryl3,materialL3)
 leg3.position.set(-1.2,1,5.8)
 const geometryl4 = new THREE.BoxGeometry(0.3, 3, 0.3)
 const materialL4 = new THREE.MeshBasicMaterial({color : 0x8A4117})
 const leg4=  new THREE.Mesh(geometryl4,materialL4)
 leg4.position.set(-1.2,1,4.2)
//chair 2
 const geometryc11 = new THREE.BoxGeometry(3, 0.2, 2)
 const materialc11 = new THREE.MeshBasicMaterial({color : 0x5C3317})
 const cube11 =  new THREE.Mesh(geometryc11,materialc11)
 cube11.position.set(0,2.5,-5)
 const geometrybb = new THREE.BoxGeometry(2.8, 2.2, 0.2)
 const materialbb = new THREE.MeshBasicMaterial({color : 0x7E3817})
 const cubebb =  new THREE.Mesh(geometrybb,materialbb)
 cubebb.position.set(0,3.5,-6)
 const geometryg = new THREE.BoxGeometry(0.3, 3, 0.3)
 const materialg = new THREE.MeshBasicMaterial({color : 0x8A4117})
 const legg=  new THREE.Mesh(geometryg,materialg)
 legg.position.set(-1.2,1,-4.2)
 const geometryg2 = new THREE.BoxGeometry(0.3, 3, 0.3)
 const materialg2 = new THREE.MeshBasicMaterial({color : 0x8A4117})
 const legg2=  new THREE.Mesh(geometryg2,materialg2)
 legg2.position.set(1.2,1,-4.2)
 const geometryg3 = new THREE.BoxGeometry(0.3, 3, 0.3)
 const materialg3 = new THREE.MeshBasicMaterial({color : 0x8A4117})
 const legg3=  new THREE.Mesh(geometryg3,materialg3)
 legg3.position.set(1.2,1,-5.8)
 const geometryg4 = new THREE.BoxGeometry(0.3, 3, 0.3)
 const materialg4 = new THREE.MeshBasicMaterial({color : 0x8A4117})
 const legg4=  new THREE.Mesh(geometryg4,materialg4)
 legg4.position.set(-1.2,1,-5.8)
 
 scene.add(cube,regtangle,regtangle2,regtangle3,regtangle4,under,underr,under1,under11,under2,under3)
 scene.add(cubeb,cube1,leg,leg2,leg3,leg4)
 scene.add(cube11,cubebb,legg,legg2,legg3,legg4)
 const renderer = new THREE.WebGLRenderer()
 renderer.setSize(width, height)
 renderer.render(scene,camera)
 
const controls = new OrbitControls( camera, renderer.domElement );
controls.update()

  function rotation(){
    //cube.rotation.x += 0.1,cube.rotation.y +=0.02,cube.rotation.z +=0.003;
    renderer.render(scene,camera)
  }
  renderer.setAnimationLoop(rotation)
  document.body.append(renderer.domElement)